// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: src/api/StockService.proto

package stocktest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	OrderSide_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_src_api_StockService_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_src_api_StockService_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_MARKET OrderType = 0
	OrderType_LIMIT  OrderType = 1
	OrderType_IOC    OrderType = 2
	OrderType_FOK    OrderType = 3
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "MARKET",
		1: "LIMIT",
		2: "IOC",
		3: "FOK",
	}
	OrderType_value = map[string]int32{
		"MARKET": 0,
		"LIMIT":  1,
		"IOC":    2,
		"FOK":    3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_api_StockService_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_src_api_StockService_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{1}
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"` // e.g. "AAPL"
	Side          OrderSide              `protobuf:"varint,4,opt,name=side,proto3,enum=stock.OrderSide" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=stock.OrderType" json:"type,omitempty"`
	Quantity      int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"` // used for limit orders
	TimestampMs   int64                  `protobuf:"varint,8,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_src_api_StockService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *OrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_MARKET
}

func (x *OrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,4,rep,name=trades,proto3" json:"trades,omitempty"` // trades produced immediately (may be empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_src_api_StockService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *OrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type OrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusRequest) Reset() {
	*x = OrderStatusRequest{}
	mi := &file_src_api_StockService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusRequest) ProtoMessage() {}

func (x *OrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusRequest.ProtoReflect.Descriptor instead.
func (*OrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	RemainingQty  int64                  `protobuf:"varint,3,opt,name=remaining_qty,json=remainingQty,proto3" json:"remaining_qty,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "open", "filled", "cancelled"
	Trades        []*Trade               `protobuf:"bytes,5,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusResponse) Reset() {
	*x = OrderStatusResponse{}
	mi := &file_src_api_StockService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusResponse) ProtoMessage() {}

func (x *OrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{3}
}

func (x *OrderStatusResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatusResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *OrderStatusResponse) GetRemainingQty() int64 {
	if x != nil {
		return x.RemainingQty
	}
	return 0
}

func (x *OrderStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderStatusResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyOrderId    string                 `protobuf:"bytes,1,opt,name=buy_order_id,json=buyOrderId,proto3" json:"buy_order_id,omitempty"`
	SellOrderId   string                 `protobuf:"bytes,2,opt,name=sell_order_id,json=sellOrderId,proto3" json:"sell_order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"varint,5,opt,name=qty,proto3" json:"qty,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_src_api_StockService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{4}
}

func (x *Trade) GetBuyOrderId() string {
	if x != nil {
		return x.BuyOrderId
	}
	return ""
}

func (x *Trade) GetSellOrderId() string {
	if x != nil {
		return x.SellOrderId
	}
	return ""
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Trade) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type MarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // subscribe to list (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataRequest) Reset() {
	*x = MarketDataRequest{}
	mi := &file_src_api_StockService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataRequest) ProtoMessage() {}

func (x *MarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataRequest.ProtoReflect.Descriptor instead.
func (*MarketDataRequest) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{5}
}

func (x *MarketDataRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type MarketDataUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	LastQty       int64                  `protobuf:"varint,3,opt,name=last_qty,json=lastQty,proto3" json:"last_qty,omitempty"`
	TopBids       []*PriceLevel          `protobuf:"bytes,4,rep,name=top_bids,json=topBids,proto3" json:"top_bids,omitempty"` // maybe top 5
	TopAsks       []*PriceLevel          `protobuf:"bytes,5,rep,name=top_asks,json=topAsks,proto3" json:"top_asks,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataUpdate) Reset() {
	*x = MarketDataUpdate{}
	mi := &file_src_api_StockService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataUpdate) ProtoMessage() {}

func (x *MarketDataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataUpdate.ProtoReflect.Descriptor instead.
func (*MarketDataUpdate) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{6}
}

func (x *MarketDataUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketDataUpdate) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *MarketDataUpdate) GetLastQty() int64 {
	if x != nil {
		return x.LastQty
	}
	return 0
}

func (x *MarketDataUpdate) GetTopBids() []*PriceLevel {
	if x != nil {
		return x.TopBids
	}
	return nil
}

func (x *MarketDataUpdate) GetTopAsks() []*PriceLevel {
	if x != nil {
		return x.TopAsks
	}
	return nil
}

func (x *MarketDataUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_src_api_StockService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{7}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type IndexRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// criteria: "volume" or "change"
	Criterion     string `protobuf:"bytes,1,opt,name=criterion,proto3" json:"criterion,omitempty"`
	TopN          int32  `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_src_api_StockService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{8}
}

func (x *IndexRequest) GetCriterion() string {
	if x != nil {
		return x.Criterion
	}
	return ""
}

func (x *IndexRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type IndexUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Entries       []*IndexEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexUpdate) Reset() {
	*x = IndexUpdate{}
	mi := &file_src_api_StockService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexUpdate) ProtoMessage() {}

func (x *IndexUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexUpdate.ProtoReflect.Descriptor instead.
func (*IndexUpdate) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{9}
}

func (x *IndexUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *IndexUpdate) GetEntries() []*IndexEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type IndexEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	ChangePct     float64                `protobuf:"fixed64,3,opt,name=change_pct,json=changePct,proto3" json:"change_pct,omitempty"`
	Volume        int64                  `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexEntry) Reset() {
	*x = IndexEntry{}
	mi := &file_src_api_StockService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntry) ProtoMessage() {}

func (x *IndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntry.ProtoReflect.Descriptor instead.
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{10}
}

func (x *IndexEntry) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IndexEntry) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *IndexEntry) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

func (x *IndexEntry) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// Market Index Messages (like S&P 500, Sensex)
type MarketIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"` // "SP500", "SENSEX", "NASDAQ", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketIndexRequest) Reset() {
	*x = MarketIndexRequest{}
	mi := &file_src_api_StockService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketIndexRequest) ProtoMessage() {}

func (x *MarketIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketIndexRequest.ProtoReflect.Descriptor instead.
func (*MarketIndexRequest) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{11}
}

func (x *MarketIndexRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type MarketIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	IndexValue    float64                `protobuf:"fixed64,2,opt,name=index_value,json=indexValue,proto3" json:"index_value,omitempty"`          // Current index value (e.g., 4500.25)
	ChangePoints  float64                `protobuf:"fixed64,3,opt,name=change_points,json=changePoints,proto3" json:"change_points,omitempty"`    // Change in points from previous day
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"` // Percentage change
	DayHigh       float64                `protobuf:"fixed64,5,opt,name=day_high,json=dayHigh,proto3" json:"day_high,omitempty"`                   // Today's high
	DayLow        float64                `protobuf:"fixed64,6,opt,name=day_low,json=dayLow,proto3" json:"day_low,omitempty"`                      // Today's low
	DayOpen       float64                `protobuf:"fixed64,7,opt,name=day_open,json=dayOpen,proto3" json:"day_open,omitempty"`                   // Today's opening value
	TimestampMs   int64                  `protobuf:"varint,8,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Constituents  []*IndexConstituent    `protobuf:"bytes,9,rep,name=constituents,proto3" json:"constituents,omitempty"` // Top 5 stocks that make up the index
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketIndexResponse) Reset() {
	*x = MarketIndexResponse{}
	mi := &file_src_api_StockService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketIndexResponse) ProtoMessage() {}

func (x *MarketIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketIndexResponse.ProtoReflect.Descriptor instead.
func (*MarketIndexResponse) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{12}
}

func (x *MarketIndexResponse) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *MarketIndexResponse) GetIndexValue() float64 {
	if x != nil {
		return x.IndexValue
	}
	return 0
}

func (x *MarketIndexResponse) GetChangePoints() float64 {
	if x != nil {
		return x.ChangePoints
	}
	return 0
}

func (x *MarketIndexResponse) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *MarketIndexResponse) GetDayHigh() float64 {
	if x != nil {
		return x.DayHigh
	}
	return 0
}

func (x *MarketIndexResponse) GetDayLow() float64 {
	if x != nil {
		return x.DayLow
	}
	return 0
}

func (x *MarketIndexResponse) GetDayOpen() float64 {
	if x != nil {
		return x.DayOpen
	}
	return 0
}

func (x *MarketIndexResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MarketIndexResponse) GetConstituents() []*IndexConstituent {
	if x != nil {
		return x.Constituents
	}
	return nil
}

type MarketIndexUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	IndexValue    float64                `protobuf:"fixed64,2,opt,name=index_value,json=indexValue,proto3" json:"index_value,omitempty"`
	ChangePoints  float64                `protobuf:"fixed64,3,opt,name=change_points,json=changePoints,proto3" json:"change_points,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	DayHigh       float64                `protobuf:"fixed64,5,opt,name=day_high,json=dayHigh,proto3" json:"day_high,omitempty"`
	DayLow        float64                `protobuf:"fixed64,6,opt,name=day_low,json=dayLow,proto3" json:"day_low,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,7,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Constituents  []*IndexConstituent    `protobuf:"bytes,8,rep,name=constituents,proto3" json:"constituents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketIndexUpdate) Reset() {
	*x = MarketIndexUpdate{}
	mi := &file_src_api_StockService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketIndexUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketIndexUpdate) ProtoMessage() {}

func (x *MarketIndexUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketIndexUpdate.ProtoReflect.Descriptor instead.
func (*MarketIndexUpdate) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{13}
}

func (x *MarketIndexUpdate) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *MarketIndexUpdate) GetIndexValue() float64 {
	if x != nil {
		return x.IndexValue
	}
	return 0
}

func (x *MarketIndexUpdate) GetChangePoints() float64 {
	if x != nil {
		return x.ChangePoints
	}
	return 0
}

func (x *MarketIndexUpdate) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *MarketIndexUpdate) GetDayHigh() float64 {
	if x != nil {
		return x.DayHigh
	}
	return 0
}

func (x *MarketIndexUpdate) GetDayLow() float64 {
	if x != nil {
		return x.DayLow
	}
	return 0
}

func (x *MarketIndexUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MarketIndexUpdate) GetConstituents() []*IndexConstituent {
	if x != nil {
		return x.Constituents
	}
	return nil
}

type IndexConstituent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`                                    // Weight in index calculation (0.0 to 1.0)
	Contribution  float64                `protobuf:"fixed64,4,opt,name=contribution,proto3" json:"contribution,omitempty"`                        // Points contributed to index
	ChangePercent float64                `protobuf:"fixed64,5,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"` // Stock's change percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexConstituent) Reset() {
	*x = IndexConstituent{}
	mi := &file_src_api_StockService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexConstituent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexConstituent) ProtoMessage() {}

func (x *IndexConstituent) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexConstituent.ProtoReflect.Descriptor instead.
func (*IndexConstituent) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{14}
}

func (x *IndexConstituent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IndexConstituent) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *IndexConstituent) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *IndexConstituent) GetContribution() float64 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

func (x *IndexConstituent) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

// All Stocks Streaming Messages
type AllStocksRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncludeOrderBook bool                   `protobuf:"varint,1,opt,name=include_order_book,json=includeOrderBook,proto3" json:"include_order_book,omitempty"` // Whether to include bid/ask data
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AllStocksRequest) Reset() {
	*x = AllStocksRequest{}
	mi := &file_src_api_StockService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStocksRequest) ProtoMessage() {}

func (x *AllStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStocksRequest.ProtoReflect.Descriptor instead.
func (*AllStocksRequest) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{15}
}

func (x *AllStocksRequest) GetIncludeOrderBook() bool {
	if x != nil {
		return x.IncludeOrderBook
	}
	return false
}

type AllStocksUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Stocks        []*StockSnapshot       `protobuf:"bytes,2,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllStocksUpdate) Reset() {
	*x = AllStocksUpdate{}
	mi := &file_src_api_StockService_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStocksUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStocksUpdate) ProtoMessage() {}

func (x *AllStocksUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStocksUpdate.ProtoReflect.Descriptor instead.
func (*AllStocksUpdate) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{16}
}

func (x *AllStocksUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AllStocksUpdate) GetStocks() []*StockSnapshot {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type StockSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	ChangePoints  float64                `protobuf:"fixed64,3,opt,name=change_points,json=changePoints,proto3" json:"change_points,omitempty"`    // Change in price points
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"` // Percentage change
	DayHigh       float64                `protobuf:"fixed64,5,opt,name=day_high,json=dayHigh,proto3" json:"day_high,omitempty"`                   // Today's high price
	DayLow        float64                `protobuf:"fixed64,6,opt,name=day_low,json=dayLow,proto3" json:"day_low,omitempty"`                      // Today's low price
	DayOpen       float64                `protobuf:"fixed64,7,opt,name=day_open,json=dayOpen,proto3" json:"day_open,omitempty"`                   // Today's opening price
	Volume        int64                  `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`                                     // Total volume traded
	Vwap          float64                `protobuf:"fixed64,9,opt,name=vwap,proto3" json:"vwap,omitempty"`                                        // Volume weighted average price
	TopBids       []*PriceLevel          `protobuf:"bytes,10,rep,name=top_bids,json=topBids,proto3" json:"top_bids,omitempty"`                    // Top 3 bids (optional)
	TopAsks       []*PriceLevel          `protobuf:"bytes,11,rep,name=top_asks,json=topAsks,proto3" json:"top_asks,omitempty"`                    // Top 3 asks (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockSnapshot) Reset() {
	*x = StockSnapshot{}
	mi := &file_src_api_StockService_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockSnapshot) ProtoMessage() {}

func (x *StockSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_StockService_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockSnapshot.ProtoReflect.Descriptor instead.
func (*StockSnapshot) Descriptor() ([]byte, []int) {
	return file_src_api_StockService_proto_rawDescGZIP(), []int{17}
}

func (x *StockSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockSnapshot) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *StockSnapshot) GetChangePoints() float64 {
	if x != nil {
		return x.ChangePoints
	}
	return 0
}

func (x *StockSnapshot) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *StockSnapshot) GetDayHigh() float64 {
	if x != nil {
		return x.DayHigh
	}
	return 0
}

func (x *StockSnapshot) GetDayLow() float64 {
	if x != nil {
		return x.DayLow
	}
	return 0
}

func (x *StockSnapshot) GetDayOpen() float64 {
	if x != nil {
		return x.DayOpen
	}
	return 0
}

func (x *StockSnapshot) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StockSnapshot) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *StockSnapshot) GetTopBids() []*PriceLevel {
	if x != nil {
		return x.TopBids
	}
	return nil
}

func (x *StockSnapshot) GetTopAsks() []*PriceLevel {
	if x != nil {
		return x.TopAsks
	}
	return nil
}

var File_src_api_StockService_proto protoreflect.FileDescriptor

const file_src_api_StockService_proto_rawDesc = "" +
	"\n" +
	"\x1asrc/api/StockService.proto\x12\x05stock\"\xfb\x01\n" +
	"\fOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12$\n" +
	"\x04side\x18\x04 \x01(\x0e2\x10.stock.OrderSideR\x04side\x12$\n" +
	"\x04type\x18\x05 \x01(\x0e2\x10.stock.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12!\n" +
	"\ftimestamp_ms\x18\b \x01(\x03R\vtimestampMs\"\x86\x01\n" +
	"\rOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12$\n" +
	"\x06trades\x18\x04 \x03(\v2\f.stock.TradeR\x06trades\"/\n" +
	"\x12OrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xab\x01\n" +
	"\x13OrderStatusResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12#\n" +
	"\rremaining_qty\x18\x03 \x01(\x03R\fremainingQty\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12$\n" +
	"\x06trades\x18\x05 \x03(\v2\f.stock.TradeR\x06trades\"\xb0\x01\n" +
	"\x05Trade\x12 \n" +
	"\fbuy_order_id\x18\x01 \x01(\tR\n" +
	"buyOrderId\x12\"\n" +
	"\rsell_order_id\x18\x02 \x01(\tR\vsellOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x10\n" +
	"\x03qty\x18\x05 \x01(\x03R\x03qty\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\"-\n" +
	"\x11MarketDataRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xe3\x01\n" +
	"\x10MarketDataUpdate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12\x19\n" +
	"\blast_qty\x18\x03 \x01(\x03R\alastQty\x12,\n" +
	"\btop_bids\x18\x04 \x03(\v2\x11.stock.PriceLevelR\atopBids\x12,\n" +
	"\btop_asks\x18\x05 \x03(\v2\x11.stock.PriceLevelR\atopAsks\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\"4\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\"A\n" +
	"\fIndexRequest\x12\x1c\n" +
	"\tcriterion\x18\x01 \x01(\tR\tcriterion\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\x05R\x04topN\"]\n" +
	"\vIndexUpdate\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12+\n" +
	"\aentries\x18\x02 \x03(\v2\x11.stock.IndexEntryR\aentries\"z\n" +
	"\n" +
	"IndexEntry\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12\x1d\n" +
	"\n" +
	"change_pct\x18\x03 \x01(\x01R\tchangePct\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x03R\x06volume\"3\n" +
	"\x12MarketIndexRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\"\xd0\x02\n" +
	"\x13MarketIndexResponse\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x1f\n" +
	"\vindex_value\x18\x02 \x01(\x01R\n" +
	"indexValue\x12#\n" +
	"\rchange_points\x18\x03 \x01(\x01R\fchangePoints\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x19\n" +
	"\bday_high\x18\x05 \x01(\x01R\adayHigh\x12\x17\n" +
	"\aday_low\x18\x06 \x01(\x01R\x06dayLow\x12\x19\n" +
	"\bday_open\x18\a \x01(\x01R\adayOpen\x12!\n" +
	"\ftimestamp_ms\x18\b \x01(\x03R\vtimestampMs\x12;\n" +
	"\fconstituents\x18\t \x03(\v2\x17.stock.IndexConstituentR\fconstituents\"\xb3\x02\n" +
	"\x11MarketIndexUpdate\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x1f\n" +
	"\vindex_value\x18\x02 \x01(\x01R\n" +
	"indexValue\x12#\n" +
	"\rchange_points\x18\x03 \x01(\x01R\fchangePoints\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x19\n" +
	"\bday_high\x18\x05 \x01(\x01R\adayHigh\x12\x17\n" +
	"\aday_low\x18\x06 \x01(\x01R\x06dayLow\x12!\n" +
	"\ftimestamp_ms\x18\a \x01(\x03R\vtimestampMs\x12;\n" +
	"\fconstituents\x18\b \x03(\v2\x17.stock.IndexConstituentR\fconstituents\"\xac\x01\n" +
	"\x10IndexConstituent\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\"\n" +
	"\fcontribution\x18\x04 \x01(\x01R\fcontribution\x12%\n" +
	"\x0echange_percent\x18\x05 \x01(\x01R\rchangePercent\"@\n" +
	"\x10AllStocksRequest\x12,\n" +
	"\x12include_order_book\x18\x01 \x01(\bR\x10includeOrderBook\"b\n" +
	"\x0fAllStocksUpdate\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12,\n" +
	"\x06stocks\x18\x02 \x03(\v2\x14.stock.StockSnapshotR\x06stocks\"\xe9\x02\n" +
	"\rStockSnapshot\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12#\n" +
	"\rchange_points\x18\x03 \x01(\x01R\fchangePoints\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x19\n" +
	"\bday_high\x18\x05 \x01(\x01R\adayHigh\x12\x17\n" +
	"\aday_low\x18\x06 \x01(\x01R\x06dayLow\x12\x19\n" +
	"\bday_open\x18\a \x01(\x01R\adayOpen\x12\x16\n" +
	"\x06volume\x18\b \x01(\x03R\x06volume\x12\x12\n" +
	"\x04vwap\x18\t \x01(\x01R\x04vwap\x12,\n" +
	"\btop_bids\x18\n" +
	" \x03(\v2\x11.stock.PriceLevelR\atopBids\x12,\n" +
	"\btop_asks\x18\v \x03(\v2\x11.stock.PriceLevelR\atopAsks*\x1e\n" +
	"\tOrderSide\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*4\n" +
	"\tOrderType\x12\n" +
	"\n" +
	"\x06MARKET\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\a\n" +
	"\x03IOC\x10\x02\x12\a\n" +
	"\x03FOK\x10\x032\xef\x03\n" +
	"\fStockService\x128\n" +
	"\vSubmitOrder\x12\x13.stock.OrderRequest\x1a\x14.stock.OrderResponse\x12D\n" +
	"\vOrderStatus\x12\x19.stock.OrderStatusRequest\x1a\x1a.stock.OrderStatusResponse\x12G\n" +
	"\x10StreamMarketData\x12\x18.stock.MarketDataRequest\x1a\x17.stock.MarketDataUpdate0\x01\x12;\n" +
	"\x0eStreamTopIndex\x12\x13.stock.IndexRequest\x1a\x12.stock.IndexUpdate0\x01\x12G\n" +
	"\x0eGetMarketIndex\x12\x19.stock.MarketIndexRequest\x1a\x1a.stock.MarketIndexResponse\x12J\n" +
	"\x11StreamMarketIndex\x12\x19.stock.MarketIndexRequest\x1a\x18.stock.MarketIndexUpdate0\x01\x12D\n" +
	"\x0fStreamAllStocks\x12\x17.stock.AllStocksRequest\x1a\x16.stock.AllStocksUpdate0\x01B\tZ\a.;stockb\x06proto3"

var (
	file_src_api_StockService_proto_rawDescOnce sync.Once
	file_src_api_StockService_proto_rawDescData []byte
)

func file_src_api_StockService_proto_rawDescGZIP() []byte {
	file_src_api_StockService_proto_rawDescOnce.Do(func() {
		file_src_api_StockService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_api_StockService_proto_rawDesc), len(file_src_api_StockService_proto_rawDesc)))
	})
	return file_src_api_StockService_proto_rawDescData
}

var file_src_api_StockService_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_api_StockService_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_src_api_StockService_proto_goTypes = []any{
	(OrderSide)(0),              // 0: stock.OrderSide
	(OrderType)(0),              // 1: stock.OrderType
	(*OrderRequest)(nil),        // 2: stock.OrderRequest
	(*OrderResponse)(nil),       // 3: stock.OrderResponse
	(*OrderStatusRequest)(nil),  // 4: stock.OrderStatusRequest
	(*OrderStatusResponse)(nil), // 5: stock.OrderStatusResponse
	(*Trade)(nil),               // 6: stock.Trade
	(*MarketDataRequest)(nil),   // 7: stock.MarketDataRequest
	(*MarketDataUpdate)(nil),    // 8: stock.MarketDataUpdate
	(*PriceLevel)(nil),          // 9: stock.PriceLevel
	(*IndexRequest)(nil),        // 10: stock.IndexRequest
	(*IndexUpdate)(nil),         // 11: stock.IndexUpdate
	(*IndexEntry)(nil),          // 12: stock.IndexEntry
	(*MarketIndexRequest)(nil),  // 13: stock.MarketIndexRequest
	(*MarketIndexResponse)(nil), // 14: stock.MarketIndexResponse
	(*MarketIndexUpdate)(nil),   // 15: stock.MarketIndexUpdate
	(*IndexConstituent)(nil),    // 16: stock.IndexConstituent
	(*AllStocksRequest)(nil),    // 17: stock.AllStocksRequest
	(*AllStocksUpdate)(nil),     // 18: stock.AllStocksUpdate
	(*StockSnapshot)(nil),       // 19: stock.StockSnapshot
}
var file_src_api_StockService_proto_depIdxs = []int32{
	0,  // 0: stock.OrderRequest.side:type_name -> stock.OrderSide
	1,  // 1: stock.OrderRequest.type:type_name -> stock.OrderType
	6,  // 2: stock.OrderResponse.trades:type_name -> stock.Trade
	6,  // 3: stock.OrderStatusResponse.trades:type_name -> stock.Trade
	9,  // 4: stock.MarketDataUpdate.top_bids:type_name -> stock.PriceLevel
	9,  // 5: stock.MarketDataUpdate.top_asks:type_name -> stock.PriceLevel
	12, // 6: stock.IndexUpdate.entries:type_name -> stock.IndexEntry
	16, // 7: stock.MarketIndexResponse.constituents:type_name -> stock.IndexConstituent
	16, // 8: stock.MarketIndexUpdate.constituents:type_name -> stock.IndexConstituent
	19, // 9: stock.AllStocksUpdate.stocks:type_name -> stock.StockSnapshot
	9,  // 10: stock.StockSnapshot.top_bids:type_name -> stock.PriceLevel
	9,  // 11: stock.StockSnapshot.top_asks:type_name -> stock.PriceLevel
	2,  // 12: stock.StockService.SubmitOrder:input_type -> stock.OrderRequest
	4,  // 13: stock.StockService.OrderStatus:input_type -> stock.OrderStatusRequest
	7,  // 14: stock.StockService.StreamMarketData:input_type -> stock.MarketDataRequest
	10, // 15: stock.StockService.StreamTopIndex:input_type -> stock.IndexRequest
	13, // 16: stock.StockService.GetMarketIndex:input_type -> stock.MarketIndexRequest
	13, // 17: stock.StockService.StreamMarketIndex:input_type -> stock.MarketIndexRequest
	17, // 18: stock.StockService.StreamAllStocks:input_type -> stock.AllStocksRequest
	3,  // 19: stock.StockService.SubmitOrder:output_type -> stock.OrderResponse
	5,  // 20: stock.StockService.OrderStatus:output_type -> stock.OrderStatusResponse
	8,  // 21: stock.StockService.StreamMarketData:output_type -> stock.MarketDataUpdate
	11, // 22: stock.StockService.StreamTopIndex:output_type -> stock.IndexUpdate
	14, // 23: stock.StockService.GetMarketIndex:output_type -> stock.MarketIndexResponse
	15, // 24: stock.StockService.StreamMarketIndex:output_type -> stock.MarketIndexUpdate
	18, // 25: stock.StockService.StreamAllStocks:output_type -> stock.AllStocksUpdate
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_src_api_StockService_proto_init() }
func file_src_api_StockService_proto_init() {
	if File_src_api_StockService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_api_StockService_proto_rawDesc), len(file_src_api_StockService_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_api_StockService_proto_goTypes,
		DependencyIndexes: file_src_api_StockService_proto_depIdxs,
		EnumInfos:         file_src_api_StockService_proto_enumTypes,
		MessageInfos:      file_src_api_StockService_proto_msgTypes,
	}.Build()
	File_src_api_StockService_proto = out.File
	file_src_api_StockService_proto_goTypes = nil
	file_src_api_StockService_proto_depIdxs = nil
}
