/*
 * Copyright (c) 2026 Ayon Sarkar. All Rights Reserved.
 *
 * This source code is licensed under the terms found in the
 * LICENSE file in the root directory of this source tree.
 *
 * USE FOR EVALUATION ONLY. NO PRODUCTION USE OR COPYING PERMITTED.
 */

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: src/api/StockService.proto

package stocktest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockService_SubmitOrder_FullMethodName       = "/stock.StockService/SubmitOrder"
	StockService_OrderStatus_FullMethodName       = "/stock.StockService/OrderStatus"
	StockService_StreamMarketData_FullMethodName  = "/stock.StockService/StreamMarketData"
	StockService_StreamTopIndex_FullMethodName    = "/stock.StockService/StreamTopIndex"
	StockService_GetMarketIndex_FullMethodName    = "/stock.StockService/GetMarketIndex"
	StockService_StreamMarketIndex_FullMethodName = "/stock.StockService/StreamMarketIndex"
	StockService_StreamAllStocks_FullMethodName   = "/stock.StockService/StreamAllStocks"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockServiceClient interface {
	// Submit an order (unary)
	SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	// Get status for an order id
	OrderStatus(ctx context.Context, in *OrderStatusRequest, opts ...grpc.CallOption) (*OrderStatusResponse, error)
	// Server stream: market data updates for a symbol (subscribe to one or many)
	StreamMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketDataUpdate], error)
	// Server stream: top index snapshot (top N stocks by volume or change)
	StreamTopIndex(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexUpdate], error)
	// Get current market index value (like S&P 500, Sensex)
	GetMarketIndex(ctx context.Context, in *MarketIndexRequest, opts ...grpc.CallOption) (*MarketIndexResponse, error)
	// Server stream: live market index updates
	StreamMarketIndex(ctx context.Context, in *MarketIndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketIndexUpdate], error)
	// Server stream: all stocks price updates
	StreamAllStocks(ctx context.Context, in *AllStocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AllStocksUpdate], error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, StockService_SubmitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) OrderStatus(ctx context.Context, in *OrderStatusRequest, opts ...grpc.CallOption) (*OrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatusResponse)
	err := c.cc.Invoke(ctx, StockService_OrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) StreamMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketDataUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockService_ServiceDesc.Streams[0], StockService_StreamMarketData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MarketDataRequest, MarketDataUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamMarketDataClient = grpc.ServerStreamingClient[MarketDataUpdate]

func (c *stockServiceClient) StreamTopIndex(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockService_ServiceDesc.Streams[1], StockService_StreamTopIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexRequest, IndexUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamTopIndexClient = grpc.ServerStreamingClient[IndexUpdate]

func (c *stockServiceClient) GetMarketIndex(ctx context.Context, in *MarketIndexRequest, opts ...grpc.CallOption) (*MarketIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketIndexResponse)
	err := c.cc.Invoke(ctx, StockService_GetMarketIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) StreamMarketIndex(ctx context.Context, in *MarketIndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketIndexUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockService_ServiceDesc.Streams[2], StockService_StreamMarketIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MarketIndexRequest, MarketIndexUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamMarketIndexClient = grpc.ServerStreamingClient[MarketIndexUpdate]

func (c *stockServiceClient) StreamAllStocks(ctx context.Context, in *AllStocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AllStocksUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockService_ServiceDesc.Streams[3], StockService_StreamAllStocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AllStocksRequest, AllStocksUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamAllStocksClient = grpc.ServerStreamingClient[AllStocksUpdate]

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility.
type StockServiceServer interface {
	// Submit an order (unary)
	SubmitOrder(context.Context, *OrderRequest) (*OrderResponse, error)
	// Get status for an order id
	OrderStatus(context.Context, *OrderStatusRequest) (*OrderStatusResponse, error)
	// Server stream: market data updates for a symbol (subscribe to one or many)
	StreamMarketData(*MarketDataRequest, grpc.ServerStreamingServer[MarketDataUpdate]) error
	// Server stream: top index snapshot (top N stocks by volume or change)
	StreamTopIndex(*IndexRequest, grpc.ServerStreamingServer[IndexUpdate]) error
	// Get current market index value (like S&P 500, Sensex)
	GetMarketIndex(context.Context, *MarketIndexRequest) (*MarketIndexResponse, error)
	// Server stream: live market index updates
	StreamMarketIndex(*MarketIndexRequest, grpc.ServerStreamingServer[MarketIndexUpdate]) error
	// Server stream: all stocks price updates
	StreamAllStocks(*AllStocksRequest, grpc.ServerStreamingServer[AllStocksUpdate]) error
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServiceServer struct{}

func (UnimplementedStockServiceServer) SubmitOrder(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedStockServiceServer) OrderStatus(context.Context, *OrderStatusRequest) (*OrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderStatus not implemented")
}
func (UnimplementedStockServiceServer) StreamMarketData(*MarketDataRequest, grpc.ServerStreamingServer[MarketDataUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarketData not implemented")
}
func (UnimplementedStockServiceServer) StreamTopIndex(*IndexRequest, grpc.ServerStreamingServer[IndexUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTopIndex not implemented")
}
func (UnimplementedStockServiceServer) GetMarketIndex(context.Context, *MarketIndexRequest) (*MarketIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketIndex not implemented")
}
func (UnimplementedStockServiceServer) StreamMarketIndex(*MarketIndexRequest, grpc.ServerStreamingServer[MarketIndexUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarketIndex not implemented")
}
func (UnimplementedStockServiceServer) StreamAllStocks(*AllStocksRequest, grpc.ServerStreamingServer[AllStocksUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAllStocks not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}
func (UnimplementedStockServiceServer) testEmbeddedByValue()                      {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	// If the following call pancis, it indicates UnimplementedStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_SubmitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).SubmitOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_OrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).OrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_OrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).OrderStatus(ctx, req.(*OrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_StreamMarketData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MarketDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockServiceServer).StreamMarketData(m, &grpc.GenericServerStream[MarketDataRequest, MarketDataUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamMarketDataServer = grpc.ServerStreamingServer[MarketDataUpdate]

func _StockService_StreamTopIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IndexRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockServiceServer).StreamTopIndex(m, &grpc.GenericServerStream[IndexRequest, IndexUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamTopIndexServer = grpc.ServerStreamingServer[IndexUpdate]

func _StockService_GetMarketIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetMarketIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetMarketIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetMarketIndex(ctx, req.(*MarketIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_StreamMarketIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MarketIndexRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockServiceServer).StreamMarketIndex(m, &grpc.GenericServerStream[MarketIndexRequest, MarketIndexUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamMarketIndexServer = grpc.ServerStreamingServer[MarketIndexUpdate]

func _StockService_StreamAllStocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllStocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockServiceServer).StreamAllStocks(m, &grpc.GenericServerStream[AllStocksRequest, AllStocksUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamAllStocksServer = grpc.ServerStreamingServer[AllStocksUpdate]

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _StockService_SubmitOrder_Handler,
		},
		{
			MethodName: "OrderStatus",
			Handler:    _StockService_OrderStatus_Handler,
		},
		{
			MethodName: "GetMarketIndex",
			Handler:    _StockService_GetMarketIndex_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarketData",
			Handler:       _StockService_StreamMarketData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTopIndex",
			Handler:       _StockService_StreamTopIndex_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMarketIndex",
			Handler:       _StockService_StreamMarketIndex_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAllStocks",
			Handler:       _StockService_StreamAllStocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/api/StockService.proto",
}
